# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clip_arcpy.py
# Created on: 2014-08-12 17:21:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
mosaic_reclass = "mosaic_reclass"
Buffer_Pai1 = "Buffer_Pai1"
Buffer_Pai1_classe_shp = "F:\\data\\Juliana_inpe\\Ju\\Buffer_Pai1_classe.shp"

# Process: Clip
arcpy.Clip_analysis(mosaic_reclass, Buffer_Pai1, Buffer_Pai1_classe_shp, "")

