# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# bufferClipArea.py
# Created on: 2014-08-15 10:54:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.workspace = "J:\Users\juliana\Documents\RESULTADOS_DOUTORADO\Paisagens_Modelos_Smmal_Mammals\Targets_Final\Targets_VALUE_Final\Tabela_SourceTargets"

mosaic_reclass = "F:\\data\\Juliana_inpe\\mosaic_reclass.shp"

rasterList = arcpy.ListRasters()

RasterT_pai1_st1 = "C:\\Users\\John\\Documents\\ArcGIS\\Default.gdb\\RasterT_pai1_st1"
RasterT_pai1_st1_Buffer = "C:\\Users\\John\\Documents\\ArcGIS\\Default.gdb\\RasterT_pai1_st1_Buffer"
mosaic_reclass_clip_buff_pai1_shp = "F:\\data\\Juliana_inpe\\PCT_pais\\mosaic_reclass_clip_buff_pai1.shp"

# Process: Raster to Polygon

teste=rasterList[0:2]
for i in teste:
    arcpy.RasterToPolygon_conversion(i, i+'_shp', "SIMPLIFY", "VALUE")
    arcpy.Buffer_analysis(i+'_shp', i+'_shp_buffer_200m', "200 Meters", "FULL", "ROUND", "ALL", "")
    arcpy.Clip_analysis(mosaic_reclass, i+'_shp_buffer_200m', 'mosaic_reclass_'+i+'_shp_buffer_200m', "")

# Process: Clip


